# Generated by Django 3.0.8 on 2020-10-10 14:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='nama', max_length=100)),
                ('plat', models.CharField(default='000000', max_length=10)),
                ('gambar', models.ImageField(upload_to='upload_img/')),
                ('harga', models.IntegerField(default=100000)),
                ('nama_user', models.CharField(max_length=50)),
                ('lama', models.IntegerField()),
                ('tgl_pesan', models.DateField()),
                ('tgl_kembali', models.DateField()),
                ('denda', models.IntegerField()),
                ('total_bayar', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mobil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='nama', max_length=100)),
                ('plat', models.CharField(default='000000', max_length=10)),
                ('gambar', models.ImageField(upload_to='upload_img/')),
                ('gambar2', models.ImageField(upload_to='upload_img/')),
                ('gambar3', models.ImageField(upload_to='upload_img/')),
                ('gambar4', models.ImageField(upload_to='upload_img/')),
                ('tipe', models.CharField(choices=[('Covertible', 'Covertible'), ('Coupe', 'Coupe'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('MPV', 'MPV')], default='MPV', max_length=20)),
                ('harga', models.IntegerField(default=100000)),
                ('deskripsi', models.TextField(default='deskripsi')),
                ('transmisi', models.CharField(choices=[('Auto', 'Auto'), ('Manual', 'Manual')], default='Manual', max_length=10)),
                ('rating', models.IntegerField(blank=True, default=0)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=20)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('ratinged_by', models.ManyToManyField(blank=True, related_name='rating', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
