# Generated by Django 3.0.8 on 2020-10-12 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sewa_mobil', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobil',
            options={'ordering': ['harga']},
        ),
    ]
